[[plugins]]
package = "@netlify/plugin-lighthouse"
[[plugins.inputs.audits]]
output_path = "reports/index.html"
path = ""
[plugins.inputs.audits.thresholds]
accessibility = 0.5
best-practices = 0.5
performance = 0.5
seo = 0.5
[[plugins.inputs.audits]]
output_path = "reports/about.html"
path = "about/"
[plugins.inputs.audits.thresholds]
accessibility = 0.5
best-practices = 0.5
performance = 0.5
seo = 0.5
[[plugins.inputs.audits]]
output_path = "reports/contact.html"
path = "contact/"
[plugins.inputs.audits.thresholds]
accessibility = 0.5
best-practices = 0.5
performance = 0.5
seo = 0.5

[[plugins]]
package = "@netlify/plugin-sitemap"
[plugins.inputs]
exclude = ['**/reports/**/*']
trailingSlash = true